// 声明 proto 使用的语法版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.11
// source: auths.proto

// proto 包名

package auth

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`           // 令牌
	Permission    string                 `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"` // 权限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenRequest) Reset() {
	*x = CheckTokenRequest{}
	mi := &file_auths_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenRequest) ProtoMessage() {}

func (x *CheckTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenRequest.ProtoReflect.Descriptor instead.
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{0}
}

func (x *CheckTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckTokenRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type CheckTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewToken      string                 `protobuf:"bytes,1,opt,name=new_token,json=newToken,proto3" json:"new_token,omitempty"` // 新令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenResponse) Reset() {
	*x = CheckTokenResponse{}
	mi := &file_auths_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResponse) ProtoMessage() {}

func (x *CheckTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResponse.ProtoReflect.Descriptor instead.
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTokenResponse) GetNewToken() string {
	if x != nil {
		return x.NewToken
	}
	return ""
}

type GetFieldAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户ID
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"` // 表名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFieldAccessRequest) Reset() {
	*x = GetFieldAccessRequest{}
	mi := &file_auths_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldAccessRequest) ProtoMessage() {}

func (x *GetFieldAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldAccessRequest.ProtoReflect.Descriptor instead.
func (*GetFieldAccessRequest) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{2}
}

func (x *GetFieldAccessRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFieldAccessRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type GetFieldAccessResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ListVisibleFields []string               `protobuf:"bytes,1,rep,name=list_visible_fields,json=listVisibleFields,proto3" json:"list_visible_fields,omitempty"` // 列表可见字段列表，["*"]表示全部字段
	EditVisibleFields []string               `protobuf:"bytes,2,rep,name=edit_visible_fields,json=editVisibleFields,proto3" json:"edit_visible_fields,omitempty"` // 表单可见字段列表
	EditableFields    []string               `protobuf:"bytes,3,rep,name=editable_fields,json=editableFields,proto3" json:"editable_fields,omitempty"`            // 可编辑字段列表
	ReadonlyFields    []string               `protobuf:"bytes,4,rep,name=readonly_fields,json=readonlyFields,proto3" json:"readonly_fields,omitempty"`            // 只读字段列表
	ViewVisibleFields []string               `protobuf:"bytes,5,rep,name=view_visible_fields,json=viewVisibleFields,proto3" json:"view_visible_fields,omitempty"` // 查看详情可见字段列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetFieldAccessResponse) Reset() {
	*x = GetFieldAccessResponse{}
	mi := &file_auths_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldAccessResponse) ProtoMessage() {}

func (x *GetFieldAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldAccessResponse.ProtoReflect.Descriptor instead.
func (*GetFieldAccessResponse) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{3}
}

func (x *GetFieldAccessResponse) GetListVisibleFields() []string {
	if x != nil {
		return x.ListVisibleFields
	}
	return nil
}

func (x *GetFieldAccessResponse) GetEditVisibleFields() []string {
	if x != nil {
		return x.EditVisibleFields
	}
	return nil
}

func (x *GetFieldAccessResponse) GetEditableFields() []string {
	if x != nil {
		return x.EditableFields
	}
	return nil
}

func (x *GetFieldAccessResponse) GetReadonlyFields() []string {
	if x != nil {
		return x.ReadonlyFields
	}
	return nil
}

func (x *GetFieldAccessResponse) GetViewVisibleFields() []string {
	if x != nil {
		return x.ViewVisibleFields
	}
	return nil
}

type GetUserPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户ID
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"` // 表名（可选，不传则不返回字段权限）
	BusinessId    uint64                 `protobuf:"varint,3,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionRequest) Reset() {
	*x = GetUserPermissionRequest{}
	mi := &file_auths_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionRequest) ProtoMessage() {}

func (x *GetUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserPermissionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserPermissionRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetUserPermissionRequest) GetBusinessId() uint64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

type FieldPermission struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ListVisibleFields []string               `protobuf:"bytes,1,rep,name=list_visible_fields,json=listVisibleFields,proto3" json:"list_visible_fields,omitempty"` // 列表可见字段列表
	EditVisibleFields []string               `protobuf:"bytes,2,rep,name=edit_visible_fields,json=editVisibleFields,proto3" json:"edit_visible_fields,omitempty"` // 表单可见字段列表
	ViewVisibleFields []string               `protobuf:"bytes,3,rep,name=view_visible_fields,json=viewVisibleFields,proto3" json:"view_visible_fields,omitempty"` // 查看详情可见字段列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FieldPermission) Reset() {
	*x = FieldPermission{}
	mi := &file_auths_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPermission) ProtoMessage() {}

func (x *FieldPermission) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPermission.ProtoReflect.Descriptor instead.
func (*FieldPermission) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{5}
}

func (x *FieldPermission) GetListVisibleFields() []string {
	if x != nil {
		return x.ListVisibleFields
	}
	return nil
}

func (x *FieldPermission) GetEditVisibleFields() []string {
	if x != nil {
		return x.EditVisibleFields
	}
	return nil
}

func (x *FieldPermission) GetViewVisibleFields() []string {
	if x != nil {
		return x.ViewVisibleFields
	}
	return nil
}

type GetUserPermissionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessType      int64                  `protobuf:"varint,1,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`               // 数据权限类型：0=自己，1=部门，2=全部，3=自己及以下角色
	DeptId          []uint64               `protobuf:"varint,2,rep,packed,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`                    // 部门ID
	UserIds         []uint64               `protobuf:"varint,3,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`                 // 用户ID列表
	FieldPermission *FieldPermission       `protobuf:"bytes,4,opt,name=field_permission,json=fieldPermission,proto3" json:"field_permission,omitempty"` // 字段权限
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserPermissionResponse) Reset() {
	*x = GetUserPermissionResponse{}
	mi := &file_auths_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionResponse) ProtoMessage() {}

func (x *GetUserPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionResponse) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserPermissionResponse) GetAccessType() int64 {
	if x != nil {
		return x.AccessType
	}
	return 0
}

func (x *GetUserPermissionResponse) GetDeptId() []uint64 {
	if x != nil {
		return x.DeptId
	}
	return nil
}

func (x *GetUserPermissionResponse) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetUserPermissionResponse) GetFieldPermission() *FieldPermission {
	if x != nil {
		return x.FieldPermission
	}
	return nil
}

var File_auths_proto protoreflect.FileDescriptor

const file_auths_proto_rawDesc = "" +
	"\n" +
	"\vauths.proto\x12\x04auth\"I\n" +
	"\x11CheckTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\"1\n" +
	"\x12CheckTokenResponse\x12\x1b\n" +
	"\tnew_token\x18\x01 \x01(\tR\bnewToken\"O\n" +
	"\x15GetFieldAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\"\xfa\x01\n" +
	"\x16GetFieldAccessResponse\x12.\n" +
	"\x13list_visible_fields\x18\x01 \x03(\tR\x11listVisibleFields\x12.\n" +
	"\x13edit_visible_fields\x18\x02 \x03(\tR\x11editVisibleFields\x12'\n" +
	"\x0feditable_fields\x18\x03 \x03(\tR\x0eeditableFields\x12'\n" +
	"\x0freadonly_fields\x18\x04 \x03(\tR\x0ereadonlyFields\x12.\n" +
	"\x13view_visible_fields\x18\x05 \x03(\tR\x11viewVisibleFields\"s\n" +
	"\x18GetUserPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x1f\n" +
	"\vbusiness_id\x18\x03 \x01(\x04R\n" +
	"businessId\"\xa1\x01\n" +
	"\x0fFieldPermission\x12.\n" +
	"\x13list_visible_fields\x18\x01 \x03(\tR\x11listVisibleFields\x12.\n" +
	"\x13edit_visible_fields\x18\x02 \x03(\tR\x11editVisibleFields\x12.\n" +
	"\x13view_visible_fields\x18\x03 \x03(\tR\x11viewVisibleFields\"\xb2\x01\n" +
	"\x19GetUserPermissionResponse\x12\x1f\n" +
	"\vaccess_type\x18\x01 \x01(\x03R\n" +
	"accessType\x12\x17\n" +
	"\adept_id\x18\x02 \x03(\x04R\x06deptId\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\x04R\auserIds\x12@\n" +
	"\x10field_permission\x18\x04 \x01(\v2\x15.auth.FieldPermissionR\x0ffieldPermission2\xf1\x01\n" +
	"\vAuthService\x12?\n" +
	"\n" +
	"CheckToken\x12\x17.auth.CheckTokenRequest\x1a\x18.auth.CheckTokenResponse\x12K\n" +
	"\x0eGetFieldAccess\x12\x1b.auth.GetFieldAccessRequest\x1a\x1c.auth.GetFieldAccessResponse\x12T\n" +
	"\x11GetUserPermission\x12\x1e.auth.GetUserPermissionRequest\x1a\x1f.auth.GetUserPermissionResponseB\bZ\x06./authb\x06proto3"

var (
	file_auths_proto_rawDescOnce sync.Once
	file_auths_proto_rawDescData []byte
)

func file_auths_proto_rawDescGZIP() []byte {
	file_auths_proto_rawDescOnce.Do(func() {
		file_auths_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auths_proto_rawDesc), len(file_auths_proto_rawDesc)))
	})
	return file_auths_proto_rawDescData
}

var file_auths_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auths_proto_goTypes = []any{
	(*CheckTokenRequest)(nil),         // 0: auth.CheckTokenRequest
	(*CheckTokenResponse)(nil),        // 1: auth.CheckTokenResponse
	(*GetFieldAccessRequest)(nil),     // 2: auth.GetFieldAccessRequest
	(*GetFieldAccessResponse)(nil),    // 3: auth.GetFieldAccessResponse
	(*GetUserPermissionRequest)(nil),  // 4: auth.GetUserPermissionRequest
	(*FieldPermission)(nil),           // 5: auth.FieldPermission
	(*GetUserPermissionResponse)(nil), // 6: auth.GetUserPermissionResponse
}
var file_auths_proto_depIdxs = []int32{
	5, // 0: auth.GetUserPermissionResponse.field_permission:type_name -> auth.FieldPermission
	0, // 1: auth.AuthService.CheckToken:input_type -> auth.CheckTokenRequest
	2, // 2: auth.AuthService.GetFieldAccess:input_type -> auth.GetFieldAccessRequest
	4, // 3: auth.AuthService.GetUserPermission:input_type -> auth.GetUserPermissionRequest
	1, // 4: auth.AuthService.CheckToken:output_type -> auth.CheckTokenResponse
	3, // 5: auth.AuthService.GetFieldAccess:output_type -> auth.GetFieldAccessResponse
	6, // 6: auth.AuthService.GetUserPermission:output_type -> auth.GetUserPermissionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auths_proto_init() }
func file_auths_proto_init() {
	if File_auths_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auths_proto_rawDesc), len(file_auths_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auths_proto_goTypes,
		DependencyIndexes: file_auths_proto_depIdxs,
		MessageInfos:      file_auths_proto_msgTypes,
	}.Build()
	File_auths_proto = out.File
	file_auths_proto_goTypes = nil
	file_auths_proto_depIdxs = nil
}
