// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.11
// source: workflow.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessKey    string                 `protobuf:"bytes,1,opt,name=process_key,json=processKey,proto3" json:"process_key,omitempty"`
	BizType       string                 `protobuf:"bytes,2,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	BizId         uint64                 `protobuf:"varint,3,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	BizNo         string                 `protobuf:"bytes,4,opt,name=biz_no,json=bizNo,proto3" json:"biz_no,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	FormData      string                 `protobuf:"bytes,6,opt,name=form_data,json=formData,proto3" json:"form_data,omitempty"`
	StartUserId   uint64                 `protobuf:"varint,7,opt,name=start_user_id,json=startUserId,proto3" json:"start_user_id,omitempty"`
	StartUserName string                 `protobuf:"bytes,8,opt,name=start_user_name,json=startUserName,proto3" json:"start_user_name,omitempty"`
	StartDeptId   uint64                 `protobuf:"varint,9,opt,name=start_dept_id,json=startDeptId,proto3" json:"start_dept_id,omitempty"`
	BusinessId    int64                  `protobuf:"varint,10,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	DeptId        int64                  `protobuf:"varint,11,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	CreateBy      int64                  `protobuf:"varint,12,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceRequest) Reset() {
	*x = StartInstanceRequest{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceRequest) ProtoMessage() {}

func (x *StartInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceRequest.ProtoReflect.Descriptor instead.
func (*StartInstanceRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *StartInstanceRequest) GetProcessKey() string {
	if x != nil {
		return x.ProcessKey
	}
	return ""
}

func (x *StartInstanceRequest) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *StartInstanceRequest) GetBizId() uint64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *StartInstanceRequest) GetBizNo() string {
	if x != nil {
		return x.BizNo
	}
	return ""
}

func (x *StartInstanceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StartInstanceRequest) GetFormData() string {
	if x != nil {
		return x.FormData
	}
	return ""
}

func (x *StartInstanceRequest) GetStartUserId() uint64 {
	if x != nil {
		return x.StartUserId
	}
	return 0
}

func (x *StartInstanceRequest) GetStartUserName() string {
	if x != nil {
		return x.StartUserName
	}
	return ""
}

func (x *StartInstanceRequest) GetStartDeptId() uint64 {
	if x != nil {
		return x.StartDeptId
	}
	return 0
}

func (x *StartInstanceRequest) GetBusinessId() int64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *StartInstanceRequest) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *StartInstanceRequest) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

type StartInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    uint64                 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceResponse) Reset() {
	*x = StartInstanceResponse{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceResponse) ProtoMessage() {}

func (x *StartInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceResponse.ProtoReflect.Descriptor instead.
func (*StartInstanceResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *StartInstanceResponse) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\bworkflow\"\xfa\x02\n" +
	"\x14StartInstanceRequest\x12\x1f\n" +
	"\vprocess_key\x18\x01 \x01(\tR\n" +
	"processKey\x12\x19\n" +
	"\bbiz_type\x18\x02 \x01(\tR\abizType\x12\x15\n" +
	"\x06biz_id\x18\x03 \x01(\x04R\x05bizId\x12\x15\n" +
	"\x06biz_no\x18\x04 \x01(\tR\x05bizNo\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1b\n" +
	"\tform_data\x18\x06 \x01(\tR\bformData\x12\"\n" +
	"\rstart_user_id\x18\a \x01(\x04R\vstartUserId\x12&\n" +
	"\x0fstart_user_name\x18\b \x01(\tR\rstartUserName\x12\"\n" +
	"\rstart_dept_id\x18\t \x01(\x04R\vstartDeptId\x12\x1f\n" +
	"\vbusiness_id\x18\n" +
	" \x01(\x03R\n" +
	"businessId\x12\x17\n" +
	"\adept_id\x18\v \x01(\x03R\x06deptId\x12\x1b\n" +
	"\tcreate_by\x18\f \x01(\x03R\bcreateBy\"8\n" +
	"\x15StartInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x04R\n" +
	"instanceId2c\n" +
	"\x0fInstanceService\x12P\n" +
	"\rStartInstance\x12\x1e.workflow.StartInstanceRequest\x1a\x1f.workflow.StartInstanceResponseB\fZ\n" +
	"./workflowb\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workflow_proto_goTypes = []any{
	(*StartInstanceRequest)(nil),  // 0: workflow.StartInstanceRequest
	(*StartInstanceResponse)(nil), // 1: workflow.StartInstanceResponse
}
var file_workflow_proto_depIdxs = []int32{
	0, // 0: workflow.InstanceService.StartInstance:input_type -> workflow.StartInstanceRequest
	1, // 1: workflow.InstanceService.StartInstance:output_type -> workflow.StartInstanceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
