// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.11
// source: configcenter.proto

package configcenter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey   string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_configcenter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[string]string      `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_configcenter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

type GetConfigInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    string                 `protobuf:"bytes,1,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigInfoRequest) Reset() {
	*x = GetConfigInfoRequest{}
	mi := &file_configcenter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigInfoRequest) ProtoMessage() {}

func (x *GetConfigInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigInfoRequest.ProtoReflect.Descriptor instead.
func (*GetConfigInfoRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigInfoRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

type GetConfigInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigValue   string                 `protobuf:"bytes,1,opt,name=config_value,json=configValue,proto3" json:"config_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigInfoResponse) Reset() {
	*x = GetConfigInfoResponse{}
	mi := &file_configcenter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigInfoResponse) ProtoMessage() {}

func (x *GetConfigInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigInfoResponse.ProtoReflect.Descriptor instead.
func (*GetConfigInfoResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigInfoResponse) GetConfigValue() string {
	if x != nil {
		return x.ConfigValue
	}
	return ""
}

var File_configcenter_proto protoreflect.FileDescriptor

const file_configcenter_proto_rawDesc = "" +
	"\n" +
	"\x12configcenter.proto\x12\fconfigcenter\"5\n" +
	"\x10GetConfigRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\"\x97\x01\n" +
	"\x11GetConfigResponse\x12F\n" +
	"\aconfigs\x18\x01 \x03(\v2,.configcenter.GetConfigResponse.ConfigsEntryR\aconfigs\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x14GetConfigInfoRequest\x12\x1f\n" +
	"\vconfig_type\x18\x01 \x01(\tR\n" +
	"configType\":\n" +
	"\x15GetConfigInfoResponse\x12!\n" +
	"\fconfig_value\x18\x01 \x01(\tR\vconfigValue2\xba\x01\n" +
	"\x10ConfigApiService\x12L\n" +
	"\tGetConfig\x12\x1e.configcenter.GetConfigRequest\x1a\x1f.configcenter.GetConfigResponse\x12X\n" +
	"\rGetConfigInfo\x12\".configcenter.GetConfigInfoRequest\x1a#.configcenter.GetConfigInfoResponseB\x10Z\x0e./configcenterb\x06proto3"

var (
	file_configcenter_proto_rawDescOnce sync.Once
	file_configcenter_proto_rawDescData []byte
)

func file_configcenter_proto_rawDescGZIP() []byte {
	file_configcenter_proto_rawDescOnce.Do(func() {
		file_configcenter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configcenter_proto_rawDesc), len(file_configcenter_proto_rawDesc)))
	})
	return file_configcenter_proto_rawDescData
}

var file_configcenter_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_configcenter_proto_goTypes = []any{
	(*GetConfigRequest)(nil),      // 0: configcenter.GetConfigRequest
	(*GetConfigResponse)(nil),     // 1: configcenter.GetConfigResponse
	(*GetConfigInfoRequest)(nil),  // 2: configcenter.GetConfigInfoRequest
	(*GetConfigInfoResponse)(nil), // 3: configcenter.GetConfigInfoResponse
	nil,                           // 4: configcenter.GetConfigResponse.ConfigsEntry
}
var file_configcenter_proto_depIdxs = []int32{
	4, // 0: configcenter.GetConfigResponse.configs:type_name -> configcenter.GetConfigResponse.ConfigsEntry
	0, // 1: configcenter.ConfigApiService.GetConfig:input_type -> configcenter.GetConfigRequest
	2, // 2: configcenter.ConfigApiService.GetConfigInfo:input_type -> configcenter.GetConfigInfoRequest
	1, // 3: configcenter.ConfigApiService.GetConfig:output_type -> configcenter.GetConfigResponse
	3, // 4: configcenter.ConfigApiService.GetConfigInfo:output_type -> configcenter.GetConfigInfoResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_configcenter_proto_init() }
func file_configcenter_proto_init() {
	if File_configcenter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configcenter_proto_rawDesc), len(file_configcenter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configcenter_proto_goTypes,
		DependencyIndexes: file_configcenter_proto_depIdxs,
		MessageInfos:      file_configcenter_proto_msgTypes,
	}.Build()
	File_configcenter_proto = out.File
	file_configcenter_proto_goTypes = nil
	file_configcenter_proto_depIdxs = nil
}
